"""One recorded DLC sequence as a reze-design scene zip - what reze-design's own
"Export scene" writes and "Import scene" reads: scene.json beside its files.

    python agtools/dlc_reze_scene.py AG_dlc_play/<skin>-<角色>-<皮肤名> [--seq touch1 ...] [--verify]
    python ag.py reze AG_dlc_play/<skin>-<角色>-<皮肤名>

Reads the recording the compare page plays (web/data: AGDlcRecord's scene.json,
<seq>.frames.jsonl/.bin, dlc_web.py's translated shaders) and the earlier
pipeline's AG_dlc_scene/<skin>/<seq>/{character.vmd,camera.vmd,audio.wav}. Writes, per sequence,
<dlc>/reze/<dlc>-<seq>.zip:

    scene.json                 a scene PATCH (reze-design lib/scene-patch.ts):
                               "patch": true, so Import merges it into the open
                               scene - her model and materials stay, her motion
                               becomes character.vmd (assets.castMotion) - and
                               only the fields below are written; props and effects
                               carry origin/stage = <dlc>, so touch2 over touch1
                               replaces touch1's
    stage/                     the static game stage (stage_native.py), named by
                               assets.nativeStage
    props/<name>/<name>.pmx    one prop per moving object group of the sequence
    props/<name>/<name>.vmd    its motion: a bone per part, scale + on/off as morphs
    props/<name>/look.json     the game's materials (engine setModelNativeLook),
                               named by the prop's `look`
    props/<name>/tex/ shaders/ what the PMX and the look name
    character.vmd camera.vmd audio.wav
                               her retargeted motion (face included), the camera
                               and the voice: all three, or none when any is
                               missing (the scene then keeps its own)

    props/particle_emitters/   the particle systems' emitters as ps<k>_NNN point
                               bones, particle_emitters.lights.json (each effect's
                               WGSL, pictures and class) and particles/*.png
                               (dlc_particles.py); the effects themselves are in
                               settings.background.effects, by value

Props are the renderers under the character's root (Char/<root>/...) that are
neither the character (SimPipeline/Character/* materials) nor particle systems:
one prop per group folder under Char/<root>/<seq>/<group>/, and one per renderer
she carries elsewhere in her hierarchy (the cup). Particle systems - hers and the
stage's - become reze effects generated by reze-design's own particleEffectWgsl
(dlc_particles.py); a mesh particle holding one still particle (X306a's hologram
sphere) becomes a prop at its recorded pose. The character herself is not in the
scene - the user's model is - but her motion is: character.vmd, retargeted for
the user's models, lands on the scene's first cast member.

Coordinates: game (x, y, z) -> PMX (-x, y, -z) * 8, a half turn about Y (winding
and handedness unchanged), the map the camera VMDs use. UV v -> 1 - v.

A part's motion is its world matrix per frame, T R S. The PMX holds the part at a
rest pose (a frame it is on, at each axis's largest scale); its bone carries
T and R as VMD keys; S, which VMD cannot key, is three vertex morphs per part
(<part>_sx/_sy/_sz, weight w scales that rest-local axis by 1 - w), and a part
that is off has all three at 1 - collapsed onto its bone.
"""
from __future__ import annotations

import argparse
import io
import json
import math
import os
import re
import struct
import sys
import tempfile
import zipfile

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dlc_particles  # noqa: E402
import stage_native  # noqa: E402

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# per sequence, from AG_dlc_scene/<skin>/<seq>/: written together or not at all
SEQUENCE_FILES = ("character.vmd", "camera.vmd", "audio.wav")
SCALE = 8.0  # PMX units per game unit (one scene scale)
FLIP = np.diag([-1.0, 1.0, -1.0])  # game -> PMX axes (a half turn about Y)
RATE = 30
ROOT_BONE = "全ての親"
AXES = "xyz"


# ---------------------------------------------------------------- recording
def mat4(a):
    """Column-major 16 -> row-major 4x4."""
    return np.array(a, dtype=np.float64).reshape(4, 4).T


def load_frames(data, seq):
    frames = [json.loads(l) for l in open(os.path.join(data, f"{seq}.frames.jsonl"), encoding="utf-8") if l.strip()]
    blob = open(os.path.join(data, f"{seq}.frames.bin"), "rb").read()
    return frames, blob


def dense_tracks(frames, blob, scene, rids):
    """Per renderer: on[n] (bool), M[n,4,4] (game world, row-major), and its full
    record state per frame (mats, mpb, layerBits). Skinned renderers (one bone):
    bone localToWorld x bindpose[0]."""
    meshes = {m["id"]: m for m in scene["meshes"]}
    rends = {r["id"]: r for r in scene["renderers"]}
    n = len(frames)
    out = {}
    for rid in rids:
        r = rends[rid]
        on = np.zeros(n, bool)
        M = np.tile(np.eye(4), (n, 1, 1))
        states = []
        cur, have = {}, False
        bp = None
        if r["kind"] == "skinned":
            bps = meshes[r["mesh"]].get("bindposes") or []
            if len(bps) != 1:
                print(f"  warning: {r['path']} has {len(bps)} bones; the prop follows bone 0 only")
            bp = mat4(bps[0]) if bps else np.eye(4)
        for i, fr in enumerate(frames):
            rec = fr["r"].get(rid)
            if rec:
                cur.update({k: v for k, v in rec.items() if k not in ("bones", "particles", "blend")})
                if r["kind"] == "skinned" and rec.get("bones"):
                    off, _cnt = rec["bones"]
                    bone = mat4(np.frombuffer(blob, np.float32, 16, off).astype(np.float64))
                    cur["_M"] = bone @ bp
                    have = True
            if r["kind"] == "skinned":
                on[i] = bool(cur.get("on")) and have
                if have:
                    M[i] = cur["_M"]
            else:
                on[i] = bool(cur.get("on")) and "m" in cur
                if "m" in cur:
                    M[i] = mat4(cur["m"])
            states.append(cur)
            cur = dict(cur)
        out[rid] = {"on": on, "M": M, "states": states}
    return out


# ---------------------------------------------------------------- names
def ascii_name(s, limit, taken, fallback="p"):
    """ASCII, at most `limit` bytes, unique within `taken`."""
    base = re.sub(r"[^A-Za-z0-9_.-]+", "_", s).strip("_") or fallback
    base = base[:limit]
    name, k = base, 2
    while name in taken:
        suffix = f"_{k}"
        name = base[:limit - len(suffix)] + suffix
        k += 1
    taken.add(name)
    return name


def discover(scene, seq_names, seq):
    """{group: [renderer ids]} of this sequence's props, and the particle renderers."""
    mats = {m["id"]: m for m in scene["materials"]}
    groups, particles = {}, []
    for r in scene["renderers"]:
        parts = r["path"].split("/")
        if parts[0] != "Char" or len(parts) < 3:
            continue
        if parts[2] in seq_names:
            if parts[2] != seq or len(parts) < 5:
                continue
            group = parts[3]
        else:
            group = parts[-1]  # something she carries (the cup): its own prop
        if r["kind"] == "particles":
            particles.append(r)
            continue
        if stage_native.is_cast(r, mats):
            continue
        groups.setdefault(group, []).append(r["id"])
    return groups, particles


# ---------------------------------------------------------------- decomposition
def trs(M3):
    """Columns -> (R proper rotation, s per-axis scale); None where degenerate."""
    s = np.linalg.norm(M3, axis=0)
    eps = 1e-7
    small = s < eps
    if small.sum() >= 2:
        return None, s
    cols = M3 / np.where(small, 1, s)
    if small.any():
        a = int(np.argmax(small))
        b, c = (a + 1) % 3, (a + 2) % 3
        cols[:, a] = np.cross(cols[:, b], cols[:, c])
        cols[:, a] /= np.linalg.norm(cols[:, a])
    # orthonormalise (the recording is float32)
    u, _, vt = np.linalg.svd(cols)
    R = u @ vt
    return R, s


def quat_of(R):
    """Rotation matrix -> quaternion (x, y, z, w)."""
    t = np.trace(R)
    if t > 0:
        k = math.sqrt(t + 1.0) * 2
        w, x, y, z = 0.25 * k, (R[2, 1] - R[1, 2]) / k, (R[0, 2] - R[2, 0]) / k, (R[1, 0] - R[0, 1]) / k
    elif R[0, 0] > R[1, 1] and R[0, 0] > R[2, 2]:
        k = math.sqrt(1.0 + R[0, 0] - R[1, 1] - R[2, 2]) * 2
        w, x, y, z = (R[2, 1] - R[1, 2]) / k, 0.25 * k, (R[0, 1] + R[1, 0]) / k, (R[0, 2] + R[2, 0]) / k
    elif R[1, 1] > R[2, 2]:
        k = math.sqrt(1.0 + R[1, 1] - R[0, 0] - R[2, 2]) * 2
        w, x, y, z = (R[0, 2] - R[2, 0]) / k, (R[0, 1] + R[1, 0]) / k, 0.25 * k, (R[1, 2] + R[2, 1]) / k
    else:
        k = math.sqrt(1.0 + R[2, 2] - R[0, 0] - R[1, 1]) * 2
        w, x, y, z = (R[1, 0] - R[0, 1]) / k, (R[0, 2] + R[2, 0]) / k, (R[1, 2] + R[2, 1]) / k, 0.25 * k
    q = np.array([x, y, z, w])
    return q / np.linalg.norm(q)


def quat_rot(q):
    x, y, z, w = q
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ])


def solve_part(track, name):
    """Rest pose, and per frame: bone translation, rotation and the three morph weights."""
    on, M = track["on"], track["M"]
    n = len(on)
    idx = np.nonzero(on)[0]
    dets = np.array([np.linalg.det(M[i, :3, :3]) for i in idx])
    mirror = np.eye(4)
    if (dets < 0).any():
        if not (dets < 0).all():
            print(f"  warning: {name} mirrors on some frames only")
        mirror = np.diag([-1.0, 1, 1, 1])  # baked into the mesh: M' = M diag(-1,1,1)
    Mm = M @ mirror
    Rs, Ss = [None] * n, np.zeros((n, 3))
    for i in idx:
        Rs[i], Ss[i] = trs(Mm[i, :3, :3])
    S_rest = Ss[idx].max(axis=0)
    ratio = np.where(S_rest > 1e-7, Ss / np.where(S_rest > 1e-7, S_rest, 1), 1)
    good = [i for i in idx if Rs[i] is not None]
    rest = max(good, key=lambda i: (ratio[i].min(), -i))
    R_rest, T_rest = Rs[rest], Mm[rest, :3, 3]
    # per frame: hold the nearest valid pose through off / degenerate frames
    R_f, T_f = [None] * n, np.zeros((n, 3))
    last = (Rs[good[0]], Mm[good[0], :3, 3])  # before the first: the first
    for i in range(n):
        if on[i] and Rs[i] is not None:
            last = (Rs[i], Mm[i, :3, 3])
        R_f[i], T_f[i] = last
    W = np.ones((n, 3))
    for i in idx:
        W[i] = np.clip(1 - np.where(S_rest > 1e-7, Ss[i] / np.where(S_rest > 1e-7, S_rest, 1), 1), 0, 1)
    head = SCALE * FLIP @ T_rest
    trans = np.array([SCALE * FLIP @ T_f[i] - head for i in range(n)])
    quats = np.array([quat_of(FLIP @ R_f[i] @ R_rest.T @ FLIP) for i in range(n)])
    for i in range(1, n):  # one hemisphere, so interpolation takes the short way
        if np.dot(quats[i], quats[i - 1]) < 0:
            quats[i] = -quats[i]
    return {"rest": int(rest), "R": R_rest, "T": T_rest, "S": S_rest, "mirror": mirror,
            "head": head, "trans": trans, "quats": quats, "weights": W, "on": on}


# ---------------------------------------------------------------- PMX
def _text(s):
    b = s.encode("utf-16-le")
    return struct.pack("<i", len(b)) + b


def write_pmx(name, textures, vertices, materials, bones, morphs, comment=""):
    """vertices: list of (pos3, nrm3, uv2, bone); materials: dicts with name, tex
    (index or -1), flags, indices (flat list); bones: (name, pos3, parent);
    morphs: (name, [(vertex, offset3)])."""
    out = io.BytesIO()
    w = out.write
    w(b"PMX " + struct.pack("<f", 2.0))
    w(bytes([8, 0, 0, 4, 4, 4, 4, 4, 4]))  # utf-16, no add-UV, 4-byte indices
    for s in (name, name, comment, comment):
        w(_text(s))
    w(struct.pack("<i", len(vertices)))
    for p, nr, uv, b in vertices:
        w(struct.pack("<3f3f2f", *p, *nr, *uv))
        w(bytes([0]) + struct.pack("<i", b))  # BDEF1
        w(struct.pack("<f", 0.0))  # edge scale
    idx = [i for m in materials for i in m["indices"]]
    w(struct.pack("<i", len(idx)))
    w(struct.pack(f"<{len(idx)}i", *idx))
    w(struct.pack("<i", len(textures)))
    for t in textures:
        w(_text(t))
    w(struct.pack("<i", len(materials)))
    for m in materials:
        w(_text(m["name"]) + _text(m["name"]))
        w(struct.pack("<4f3ff3f", 1, 1, 1, 1, 0, 0, 0, 5.0, 0.5, 0.5, 0.5))
        w(bytes([m["flags"]]))
        w(struct.pack("<4ff", 0, 0, 0, 1, 0.0))  # edge
        w(struct.pack("<ii", m["tex"], -1))
        w(bytes([0, 1, 0]))  # sphere off, shared toon 0
        w(_text(""))
        w(struct.pack("<i", len(m["indices"])))
    w(struct.pack("<i", len(bones)))
    for bn, pos, parent in bones:
        w(_text(bn) + _text(bn))
        w(struct.pack("<3fii", *pos, parent, 0))
        w(struct.pack("<H", 0x0002 | 0x0004 | 0x0008 | 0x0010))
        w(struct.pack("<3f", 0, 0, 0))  # tail offset
    w(struct.pack("<i", len(morphs)))
    for mn, offs in morphs:
        w(_text(mn) + _text(mn))
        w(bytes([4, 1]) + struct.pack("<i", len(offs)))
        for v, o in offs:
            w(struct.pack("<i3f", v, *o))
    # display frames: Root (the root bone), 表情 (the morphs), and the parts
    w(struct.pack("<i", 3))
    w(_text("Root") + _text("Root") + bytes([1]) + struct.pack("<i", 1) + bytes([0]) + struct.pack("<i", 0))
    w(_text("表情") + _text("Exp") + bytes([1]) + struct.pack("<i", len(morphs)))
    for k in range(len(morphs)):
        w(bytes([1]) + struct.pack("<i", k))
    w(_text("parts") + _text("parts") + bytes([0]) + struct.pack("<i", len(bones) - 1))
    for k in range(1, len(bones)):
        w(bytes([0]) + struct.pack("<i", k))
    w(struct.pack("<ii", 0, 0))  # rigid bodies, joints
    return out.getvalue()


def read_pmx(b):
    """Minimal PMX 2.x reader: positions, uvs, bone per vertex (BDEF1), indices,
    textures, materials, bones, vertex morphs."""
    p = 0

    def take(n):
        nonlocal p
        v = b[p:p + n]
        p += n
        return v

    assert take(4) == b"PMX "
    take(4)
    g = list(take(take(1)[0]))
    enc = "utf-16-le" if g[0] == 0 else "utf-8"
    addv, vsz, tsz, msz, bsz, mosz = g[1:7]
    fmt = {1: "b", 2: "h", 4: "i"}

    def text():
        return take(struct.unpack("<i", take(4))[0]).decode(enc)

    def ix(sz, unsigned=False):
        f = fmt[sz]
        return struct.unpack("<" + (f.upper() if unsigned and sz < 4 else f), take(sz))[0]

    name = text()
    text(), text(), text()
    nv = struct.unpack("<i", take(4))[0]
    pos, uv, vb = np.zeros((nv, 3)), np.zeros((nv, 2)), np.zeros(nv, int)
    for i in range(nv):
        pos[i] = struct.unpack("<3f", take(12))
        take(12)
        uv[i] = struct.unpack("<2f", take(8))
        take(16 * addv)
        wt = take(1)[0]
        assert wt == 0, "BDEF1 only"
        vb[i] = ix(bsz)
        take(4)
    ni = struct.unpack("<i", take(4))[0]
    idx = [ix(vsz, True) for _ in range(ni)]
    texs = [text() for _ in range(struct.unpack("<i", take(4))[0])]
    mats = []
    for _ in range(struct.unpack("<i", take(4))[0]):
        mn = text()
        text()
        take(16 + 12 + 4 + 12)
        flags = take(1)[0]
        take(16 + 4)
        ti = ix(tsz)
        ix(tsz)
        take(1)
        shared = take(1)[0]
        take(1) if shared else ix(tsz)
        text()
        mats.append({"name": mn, "tex": texs[ti] if ti >= 0 else None, "flags": flags,
                     "count": struct.unpack("<i", take(4))[0]})
    bones = []
    for _ in range(struct.unpack("<i", take(4))[0]):
        bn = text()
        text()
        bp = struct.unpack("<3f", take(12))
        parent = ix(bsz)
        take(4)
        fl = struct.unpack("<H", take(2))[0]
        take(bsz) if fl & 1 else take(12)
        assert not fl & ~0x1F, "plain bones only"
        bones.append({"name": bn, "pos": np.array(bp), "parent": parent})
    morphs = {}
    for _ in range(struct.unpack("<i", take(4))[0]):
        mn = text()
        text()
        _panel, kind = take(2)
        assert kind == 1
        offs = []
        for _ in range(struct.unpack("<i", take(4))[0]):
            v = ix(vsz, True)
            offs.append((v, np.array(struct.unpack("<3f", take(12)))))
        morphs[mn] = offs
    return {"name": name, "pos": pos, "uv": uv, "bone": vb, "indices": idx, "textures": texs,
            "materials": mats, "bones": bones, "morphs": morphs}


# ---------------------------------------------------------------- VMD
LINEAR = bytes([20, 20, 20, 20, 20, 20, 20, 20, 107, 107, 107, 107, 107, 107, 107, 107])
BONE_INTERP = b"".join(LINEAR[k:] + bytes(k) for k in range(4))


def _sjis(s, n):
    b = s.encode("shift_jis")
    if len(b) > n:
        raise ValueError(f"VMD name {s!r} is over {n} bytes")
    return b + bytes(n - len(b))


def write_vmd(model, bone_keys, morph_keys):
    """bone_keys: (name, frame, pos3, quat xyzw); morph_keys: (name, frame, weight)."""
    out = io.BytesIO()
    out.write(_sjis("Vocaloid Motion Data 0002", 30))
    mb = model.encode("shift_jis")[:20]
    out.write(mb + bytes(20 - len(mb)))
    out.write(struct.pack("<I", len(bone_keys)))
    for bn, f, p, q in bone_keys:
        out.write(_sjis(bn, 15) + struct.pack("<I3f4f", f, *p, *q) + BONE_INTERP)
    out.write(struct.pack("<I", len(morph_keys)))
    for mn, f, wt in morph_keys:
        out.write(_sjis(mn, 15) + struct.pack("<If", f, wt))
    out.write(struct.pack("<III", 0, 0, 0))  # camera, light, shadow
    out.write(struct.pack("<I", 0))  # IK
    return out.getvalue()


def read_vmd(b):
    p = 30
    model = b[p:p + 20].split(b"\0")[0].decode("shift_jis", "replace")
    p += 20
    nb = struct.unpack_from("<I", b, p)[0]
    p += 4
    bones = {}
    for _ in range(nb):
        bn = b[p:p + 15].split(b"\0")[0].decode("shift_jis")
        f, *v = struct.unpack_from("<I3f4f", b, p + 15)
        assert b[p + 47:p + 111] == BONE_INTERP
        bones.setdefault(bn, []).append((f, np.array(v[:3]), np.array(v[3:])))
        p += 111
    nm = struct.unpack_from("<I", b, p)[0]
    p += 4
    morphs = {}
    for _ in range(nm):
        mn = b[p:p + 15].split(b"\0")[0].decode("shift_jis")
        f, wt = struct.unpack_from("<If", b, p + 15)
        morphs.setdefault(mn, []).append((f, wt))
        p += 23
    for d in (bones, morphs):
        for k in d:
            d[k].sort(key=lambda e: e[0])
    return {"model": model, "bones": bones, "morphs": morphs}


def keep_frames(vals, tol=1e-6):
    """Frames to key: where the value differs from either neighbour (holds keep
    their two ends), plus the first and last."""
    n = len(vals)
    keep = []
    for i in range(n):
        if i == 0 or i == n - 1:
            keep.append(i)
            continue
        if np.abs(vals[i] - vals[i - 1]).max() > tol or np.abs(vals[i] - vals[i + 1]).max() > tol:
            keep.append(i)
    return keep


# ---------------------------------------------------------------- one prop
def mesh_arrays(data, mesh):
    raw = open(os.path.join(data, "meshes", f"{mesh['id']}.bin"), "rb").read()
    n = mesh["vertexCount"]

    def stream(sem):
        if sem not in mesh["streams"]:
            return None
        off, dim = mesh["streams"][sem]
        return np.frombuffer(raw, np.float32, n * dim, off).reshape(n, dim).astype(np.float64)

    subs = []
    for sm in mesh["submeshes"]:
        if sm.get("topology", "Triangles") != "Triangles":
            print(f"  warning: {mesh['name']} submesh topology {sm['topology']} skipped")
            subs.append(None)
            continue
        subs.append(np.frombuffer(raw, np.uint32, sm["count"], sm["offset"]).astype(np.int64))
    return stream("POSITION"), stream("NORMAL"), stream("TEXCOORD0"), subs


def material_values(m, tex_info, mpb, flip_v=True):
    """stage_native's material handling, with the renderer's property block on top.
    _ST's v is remapped to PMX's flipped v: Unity's v*s + o sampled on a v-up image
    equals v'*s + (1 - s - o) on PMX's v' = 1 - v over the same image top down."""
    values, slots = {}, {}
    props = dict(m["props"])
    for k, v in (mpb or {}).items():
        if isinstance(v, dict) and "tex" in v:
            base = props.get(k) if isinstance(props.get(k), dict) else {}
            props[k] = {"tex": v.get("tex"), "st": v.get("st") or base.get("st")}
        else:
            props[k] = v
    for k, v in props.items():
        if isinstance(v, dict) and "tex" in v:
            st = list(v.get("st") or [1, 1, 0, 0])
            if flip_v:
                st[3] = 1 - st[1] - st[3]
            values[f"{k}_ST"] = st
            values[f"{k}_HDR"] = [1, 1, 0, 0]
            t = tex_info.get(v["tex"]) if v.get("tex") else None
            values[f"{k}_TexelSize"] = [1 / t["width"], 1 / t["height"], t["width"], t["height"]] if t else [1, 1, 1, 1]
            if t:
                slots[k] = v["tex"]
        else:
            values[k] = v
    return values, slots


def build_prop(ctx, group, rids, tracks, taken_props):
    """The prop's files {relative path: bytes}, its windows and a summary."""
    data, scene, variants = ctx["data"], ctx["scene"], ctx["variants"]
    rends = {r["id"]: r for r in scene["renderers"]}
    meshes = {m["id"]: m for m in scene["meshes"]}
    mats = {m["id"]: m for m in scene["materials"]}
    tex_info = {t["id"]: t for t in scene["textures"]}
    name = ascii_name(group, 64, taken_props, "prop")
    n = ctx["frames"]
    files = {}
    textures, tex_index, look_tex = [], {}, {}
    used_shaders = set()

    def texture(tid):
        """PMX texture index / look key for a recorded texture, or None (HDR, cube)."""
        t = tex_info.get(tid)
        if not t or t.get("hdr") or t.get("cube") or not t["files"][0].endswith(".png"):
            if tid not in ctx["skipped_tex"]:
                print(f"  note: texture {tid} ({t and t['name']}) is HDR/cube - not carried in the look")
                ctx["skipped_tex"].add(tid)
            return None
        if tid not in tex_index:
            rel = f"tex/{tid}.png"
            files[rel] = open(os.path.join(data, "textures", t["files"][0]), "rb").read()
            tex_index[tid] = len(textures)
            textures.append(rel)
            look_tex[tid] = {"file": rel, "srgb": bool(t["srgb"])}
        return tid

    bones = [(ROOT_BONE, (0.0, 0.0, 0.0), -1)]
    vertices, pmx_mats, morphs = [], [], []
    bone_keys, morph_keys = [], []
    specs = {}
    parts = []
    taken_bones, taken_mats = set(), set()
    on_any = np.zeros(n, bool)
    for rid in sorted(rids, key=lambda s: int(s[1:])):
        tr = tracks[rid]
        if not tr["on"].any():
            continue
        r = rends[rid]
        rel_path = r["path"]
        pname = ascii_name(rel_path.split("/")[-1], 12, taken_bones)
        sol = solve_part(tr, f"{name}/{pname}")
        on_any |= tr["on"]
        bi = len(bones)
        bones.append((pname, tuple(sol["head"]), 0))
        mesh = meshes[r["mesh"]]
        P, N, UV, subs = mesh_arrays(data, mesh)
        mir = sol["mirror"][:3, :3]
        P, N = P @ mir.T, (N @ mir.T if N is not None else None)
        A = sol["R"] * sol["S"]  # R diag(S)
        world = (A @ P.T).T + sol["T"]
        vpos = SCALE * world @ FLIP.T
        if N is not None:
            inv_s = np.where(sol["S"] > 1e-7, 1 / np.where(sol["S"] > 1e-7, sol["S"], 1), 1)
            nw = (sol["R"] @ (N * inv_s).T).T @ FLIP.T
            nw /= np.maximum(np.linalg.norm(nw, axis=1, keepdims=True), 1e-12)
        else:
            nw = np.tile([0.0, 1.0, 0.0], (len(P), 1))
        uv = UV if UV is not None else np.zeros((len(P), 2))
        base = len(vertices)
        for k in range(len(P)):
            vertices.append((tuple(vpos[k]), tuple(nw[k]), (uv[k, 0], 1.0 - uv[k, 1]), bi))
        # the scale morphs: minus each vertex's extent along a rest-local axis
        rel = vpos - sol["head"]
        for a in range(3):
            e = FLIP @ sol["R"][:, a]
            d = rel @ e
            offs = [(base + k, tuple(-d[k] * e)) for k in range(len(P)) if abs(d[k]) > 1e-9]
            morphs.append((f"{pname}_s{AXES[a]}", offs))
        # materials: one per submesh, the game's own on top as a native look
        st = tr["states"][sol["rest"]]
        mat_ids = st.get("mats") or r["materials"]
        lit = [s for s in tr["states"] if s.get("on")]
        if len({json.dumps(s.get("mats") or r["materials"]) for s in lit}) > 1 or \
                len({json.dumps(s.get("mpb") or {}, sort_keys=True) for s in lit}) > 1:
            print(f"  note: {pname}: its materials or property block change during the sequence - the rest frame's are used")
        if len(mat_ids) > len(subs):
            print(f"  note: {pname}: {len(mat_ids)} materials over {len(subs)} submeshes - extra ones dropped")
        for si, tris in enumerate(subs):
            if tris is None or si >= len(mat_ids) or not mat_ids[si]:
                continue
            mid = mat_ids[si]
            gm = mats[mid]
            if np.linalg.det(sol["mirror"]) < 0:
                tris = tris.reshape(-1, 3)[:, ::-1].reshape(-1)
            values, slots = material_values(gm, tex_info, st.get("mpb"))
            look_slots = {k: texture(t) for k, t in slots.items()}
            look_slots = {k: v for k, v in look_slots.items() if v}
            main = next((look_slots[k] for k in ("_MainTex", "_AlbedoTex", "_BaseMap") if k in look_slots), None)
            passes = []
            want = gm["shader"].replace("/", "_")
            for p in variants.get(mid, []):
                if not p["variant"].startswith(want):
                    raise SystemExit(f"{mid} {gm['name']} is {gm['shader']} but variants.json gives {p['variant']}: "
                                     f"the recording is newer than the translation - rerun agtools/dlc_web.py")
                if p["lightMode"] == "SHADOWCASTER":
                    continue
                passes.append({"lightMode": p["lightMode"], "shader": p["variant"], "state": p.get("state") or {}})
                used_shaders.add(p["variant"])
            cull = next((p["state"].get("Cull", [2])[0] for p in passes if p["lightMode"] in ("FORWARDBASE", "ALWAYS")), 2)
            transparent = gm["queue"] > 2500
            flags = (0x01 if str(cull) in ("0", "Off") else 0)
            if not transparent and r.get("shadowCasting", 1):
                flags |= 0x02 | 0x04
            if not transparent and r.get("receiveShadows", 1):
                flags |= 0x08
            mname = ascii_name(f"{pname}_{gm['name']}", 64, taken_mats)
            pmx_mats.append({"name": mname, "tex": tex_index[main] if main else -1, "flags": flags,
                             "indices": (tris + base).tolist()})
            key = json.dumps([mid, values, look_slots], sort_keys=True)
            if key not in specs:
                specs[key] = {"materials": [], "game": gm["name"], "shader": gm["shader"],
                              "queue": gm["queue"] if gm["queue"] > 0 else 2000, "passes": passes,
                              "values": values, "textures": look_slots,
                              "defaults": variants.get("_textureDefaults", {}).get(gm["shader"], {})}
            specs[key]["materials"].append(mname)
        # motion
        tq = np.concatenate([sol["trans"], sol["quats"]], axis=1)
        for f in keep_frames(tq):
            bone_keys.append((pname, f, tuple(sol["trans"][f]), tuple(sol["quats"][f])))
        for a in range(3):
            wa = sol["weights"][:, a:a + 1]
            for f in keep_frames(wa):
                morph_keys.append((f"{pname}_s{AXES[a]}", f, float(wa[f, 0])))
        on = tr["on"]
        parts.append({"part": pname, "renderer": rid, "path": rel_path, "rest": sol["rest"],
                      "on": int(on.sum()), "windows": windows_of(on), "scale": sol["S"].tolist(),
                      "mirror": bool(np.linalg.det(sol["mirror"]) < 0)})
    if not parts:
        return None
    pmx = write_pmx(name, textures, vertices, pmx_mats, bones, morphs, comment=f"Aether Gazer prop {group} (ag-rip)")
    vmd = write_vmd(name, bone_keys, morph_keys)
    files[f"{name}.pmx"] = pmx
    files[f"{name}.vmd"] = vmd
    for s in sorted(used_shaders):
        for ext in (".vert.wgsl", ".frag.wgsl", ".json"):
            files[f"shaders/{s}{ext}"] = open(os.path.join(data, "shaders", s + ext), "rb").read()
    look = {"shaders": sorted(used_shaders), "textures": look_tex, "materials": list(specs.values())}
    files["look.json"] = json.dumps(look, ensure_ascii=False, indent=1).encode("utf-8")
    win = windows_of(on_any)
    return {"name": name, "group": group, "files": files, "windows": win, "parts": parts,
            "always": bool(on_any.all()), "bone_keys": len(bone_keys), "morph_keys": len(morph_keys),
            "morphs": len(morphs), "vertices": len(vertices), "materials": len(pmx_mats),
            "rids": [p["renderer"] for p in parts]}


def windows_of(on):
    """[start, end) frame runs where on."""
    out, start = [], None
    for i, v in enumerate(on):
        if v and start is None:
            start = i
        if not v and start is not None:
            out.append({"start": start, "end": i})
            start = None
    if start is not None:
        out.append({"start": start, "end": len(on)})
    return out


# ---------------------------------------------------------------- verification
def verify_prop(ctx, prop, tracks, pmx_bytes, vmd_bytes):
    """Read the PMX and VMD back, pose every frame each part is on (VMD keys
    linearly interpolated, morphs applied, bone rotation about its head), map back
    to game space and compare with the recorded world matrix on the mesh."""
    data, scene = ctx["data"], ctx["scene"]
    rends = {r["id"]: r for r in scene["renderers"]}
    meshes = {m["id"]: m for m in scene["meshes"]}
    pmx, vmd = read_pmx(pmx_bytes), read_vmd(vmd_bytes)
    n = ctx["frames"]
    worst = 0.0
    checked = 0

    def sample(keys, f):
        lo = max((k for k in keys if k[0] <= f), key=lambda k: k[0])
        hi = [k for k in keys if k[0] >= f]
        hi = min(hi, key=lambda k: k[0]) if hi else lo
        if hi[0] == lo[0]:
            return lo[1:]
        t = (f - lo[0]) / (hi[0] - lo[0])
        return tuple((1 - t) * np.asarray(a) + t * np.asarray(b) for a, b in zip(lo[1:], hi[1:]))

    for bi, b in enumerate(pmx["bones"]):
        if bi == 0:
            continue
        part = next(p for p in prop["parts"] if p["part"] == b["name"])
        tr = tracks[part["renderer"]]
        verts = np.nonzero(pmx["bone"] == bi)[0]
        rest = pmx["pos"][verts]
        offs = {}
        for a in AXES:
            o = np.zeros((len(pmx["pos"]), 3))
            for v, d in pmx["morphs"][f"{b['name']}_s{a}"]:
                o[v] = d
            offs[a] = o[verts]
        P, _, _, _ = mesh_arrays(data, meshes[rends[part["renderer"]]["mesh"]])
        # the recorded matrix on the mesh as recorded (a mirror is baked into the PMX)
        Ph = np.c_[P, np.ones(len(P))]
        for f in np.nonzero(tr["on"])[0]:
            t, q = sample(vmd["bones"][b["name"]], f)
            q = np.asarray(q) / np.linalg.norm(q)
            w = {a: float(sample([(k[0], k[1]) for k in vmd["morphs"][f"{b['name']}_s{a}"]], f)[0]) for a in AXES}
            v = rest + sum(w[a] * offs[a] for a in AXES)
            posed = b["pos"] + t + (quat_rot(q) @ (v - b["pos"]).T).T
            game = (FLIP @ posed.T).T / SCALE
            want = (tr["M"][f] @ Ph.T).T[:, :3]
            # the PMX vertex order is the mesh's: verts are base..base+len
            err = np.abs(game - want).max()
            worst = max(worst, err)
            checked += 1
    return worst, checked


# ---------------------------------------------------------------- scene.json
def sun_of(stage_pkg):
    """The stage's main light as the app's sun: the engine direction is game
    (-dx, dy, -dz), and azimuth/elevation invert azElToDirection."""
    dx, dy, dz = stage_pkg["lights"]["main"]["direction"]
    ex, ey, ez = -dx, dy, -dz
    ln = math.sqrt(ex * ex + ey * ey + ez * ez) or 1
    ex, ey, ez = ex / ln, ey / ln, ez / ln
    el = math.degrees(math.asin(max(-1, min(1, -ey))))
    az = math.degrees(math.atan2(-ex, -ez)) % 360
    return {"color": "#ffffff", "strength": 1, "azimuth": round(az, 3), "elevation": round(el, 3), "shadow": True}


def mesh_particle_prop(ctx, r, baked, taken):
    """A mesh particle holding one still particle, as a prop: its mesh at the pose
    the recording baked it in (an affine fit of the mesh onto the baked vertices,
    which for X306a's qiu is the system's matrix times its start size)."""
    meshes = {m["id"]: m for m in ctx["scene"]["meshes"]}
    P, _, _, _ = mesh_arrays(ctx["data"], meshes[r["mesh"]])
    B = baked[0].astype(np.float64)
    if len(P) != len(B):
        print(f"  note: {r['path']}: the baked particle has {len(B)} vertices, its mesh {len(P)} - left out")
        return None, None, None
    A = np.c_[P, np.ones(len(P))]
    X, *_ = np.linalg.lstsq(A, B, rcond=None)
    err = float(np.abs(A @ X - B).max())
    M = np.eye(4)
    M[:3, :] = X.T
    n = ctx["frames"]
    track = {"on": np.ones(n, bool), "M": np.tile(M, (n, 1, 1)),
             "states": [{"on": 1, "mats": r["materials"], "mpb": {}} for _ in range(n)]}
    prop = build_prop(ctx, r["path"].split("/")[-1], [r["id"]], {r["id"]: track}, taken)
    return prop, err, track


def scene_doc(tag, props, stage_pkg, stage_dir, extra_models=(), effects=(), sequence=True):
    """A scene PATCH (reze-design lib/scene-patch.ts): JSON Merge Patch over the
    scene it is imported into, so the user's character, her motion and every
    setting this does not name stay. Only what the sequence owns is written: the
    game stage, its props and effects, the camera and the voice, and the sun,
    view, bloom and ground it is lit and shown by. Every prop and effect carries
    `tag` (the DLC), so the next take of the same DLC replaces this one's rather
    than adding to them.

    `sequence`: the take's character.vmd, camera.vmd and audio.wav, which go
    together or not at all. With them the patch sets her motion (castMotion, onto
    the scene's first cast member - the retargeted clip, face included), the
    camera and the audio; without them it names none of the three, so the scene
    keeps its own rather than ending up with a camera cut for a motion it lacks."""
    view = stage_pkg.get("view") or {}
    bloom = view.get("bloom") or {}
    models = []
    for p in props:
        m = {
            "model": f"props/{p['name']}/{p['name']}.pmx",
            "animation": f"props/{p['name']}/{p['name']}.vmd",
            "morph": None,
            "prop": True,
            "transform": {"position": [0, 0, 0], "rotation": [0, 0, 0], "scale": 1},
            # the prop's native look, bundle-relative
            "look": f"props/{p['name']}/look.json",
        }
        if not p["always"]:
            m["visibility"] = p["windows"]
        models.append(m)
    models += [dict(m) for m in extra_models]
    for m in models:
        m["origin"] = tag
    return {
        "version": 1,
        "patch": True,
        "origin": tag,
        "assets": {
            "models": models,
            **({"castMotion": {"animation": "character.vmd"},
                "cameraAnimation": "camera.vmd",
                "audio": "audio.wav"} if sequence else {}),
            # the game stage package, bundle-relative folder
            "nativeStage": stage_dir,
        },
        "settings": {
            "sun": sun_of(stage_pkg),
            # the game's bloom at the stage's own threshold: scatter 0.77, white,
            # intensity 1 are the game's constants
            "bloom": {"enabled": True, "threshold": round(bloom.get("threshold", 0.7), 4),
                      "scatter": 0.77, "intensity": 1, "color": "#ffffff"},
            # "soft" is the game's own curve
            "view": {"transform": "soft", "exposure": 0},
            # the stage brings its own floor; ours goes off (its look stays the user's)
            "ground": {"enabled": False},
            "background": {"effects": [{**e, "stage": tag} for e in effects]},
        },
    }


# ---------------------------------------------------------------- main
def stage_files(stage_dir):
    """stage.json and exactly what it names."""
    pkg = json.load(open(os.path.join(stage_dir, "stage.json"), encoding="utf-8"))
    rel = ["stage.json"]
    rel += [f"meshes/{m['id']}.bin" for m in pkg["meshes"]]
    rel += [f"textures/{f}" for t in pkg["textures"] for f in t["files"]]
    rel += [f"shaders/{s}{e}" for s in pkg["shaders"] for e in (".vert.wgsl", ".frag.wgsl", ".json")]
    return pkg, rel


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dlc", help="AG_dlc_play/<skin>-<角色>-<皮肤名>")
    ap.add_argument("--seq", nargs="*", help="sequences (default: every recorded one)")
    ap.add_argument("--scene-dir", help="per-sequence character.vmd/camera.vmd/audio.wav (default AG_dlc_scene/<skin>)")
    ap.add_argument("--stage", help="an already written stage folder to use as is (default: rewrite it)")
    ap.add_argument("--verify", action="store_true", help="read the props back and check them against the recording")
    a = ap.parse_args()
    dlc = os.path.normpath(a.dlc)
    dlc_name = os.path.basename(dlc)
    data = os.path.join(dlc, "web", "data")
    index = json.load(open(os.path.join(data, "index.json"), encoding="utf-8"))
    scene = json.load(open(os.path.join(data, "scene.json"), encoding="utf-8"))
    variants = json.load(open(os.path.join(data, "variants.json"), encoding="utf-8"))
    seq_names = [s["name"] for s in index["sequences"]]
    seqs = a.seq or seq_names
    scene_dir = a.scene_dir or os.path.join(HERE, "AG_dlc_scene", index["skin"])

    stage_dir = a.stage or stage_native.export_stage(dlc)
    stage_pkg, stage_rel = stage_files(stage_dir)

    out_dir = os.path.join(dlc, "reze")
    os.makedirs(out_dir, exist_ok=True)
    pctx = {"data": data, "scene": scene, "dlc": dlc,
            "scratch": os.path.join(tempfile.gettempdir(), "ag-rip-dlc-particles")}
    report = []
    for seq in seqs:
        print(f"== {seq}")
        frames, blob = load_frames(data, seq)
        rate = round(1 / (frames[1]["time"] - frames[0]["time"])) if len(frames) > 1 else RATE
        if rate != RATE:
            print(f"  warning: recorded at {rate}/s, keyed as {RATE}/s")
        groups, particles = discover(scene, seq_names, seq)
        rids = [r for g in groups.values() for r in g]
        tracks = dense_tracks(frames, blob, scene, rids)
        # a stage renderer that moves or switches here stays at its first state
        kinds = {r["id"]: r for r in scene["renderers"]}
        moved = sorted({rid for fr in frames[1:] for rid, rec in fr["r"].items()
                        if kinds[rid]["kind"] == "mesh" and not kinds[rid]["path"].startswith("Char/")
                        and ("m" in rec or "on" in rec)}, key=lambda s: int(s[1:]))
        for rid in moved:
            print(f"  note: stage renderer {rid} {kinds[rid]['path']} moves or switches during {seq} - the stage keeps its first state")
        ctx = {"data": data, "scene": scene, "variants": variants, "frames": len(frames), "skipped_tex": set()}
        props, taken = [], set()
        for group, g_rids in groups.items():
            p = build_prop(ctx, group, g_rids, tracks, taken)
            if p:
                props.append(p)
        ptracks = dense_tracks(frames, blob, scene, [r["id"] for r in particles])
        live_particles = [r for r in particles if ptracks[r["id"]]["on"].any()]
        stage_particles = [r for r in scene["renderers"] if r["kind"] == "particles" and not r["path"].startswith("Char/")]
        sp_tracks = dense_tracks(frames, blob, scene, [r["id"] for r in stage_particles])
        stage_particles = [r for r in stage_particles if sp_tracks[r["id"]]["on"].any()]
        fx = dlc_particles.build(pctx, frames, blob, live_particles + stage_particles, {**ptracks, **sp_tracks})
        for r, baked in fx["mesh_props"]:
            p, err, track = mesh_particle_prop(ctx, r, baked, taken)
            if p:
                tracks[r["id"]] = track
                print(f"  mesh particle {r['path']} -> prop {p['name']} (pose fit to the baked particle, max |error| {err:.1e} game units)")
                props.append(p)
        extra = [fx["model"]] if fx["model"] else []

        # her motion, the camera and the voice: all three or none
        seq_files = [(os.path.join(scene_dir, seq, f), f) for f in SEQUENCE_FILES]
        missing = [src for src, _ in seq_files if not os.path.exists(src)]
        if missing:
            print(f"  warning: {', '.join(missing)} missing - no motion, camera or audio in this zip")
            seq_files = []
        name = f"{dlc_name}-{seq}"
        doc = scene_doc(dlc_name, props, stage_pkg, "stage/", extra, fx["effects"], sequence=bool(seq_files))
        zpath = os.path.join(out_dir, f"{name}.zip")
        with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
            z.writestr("scene.json", json.dumps(doc, ensure_ascii=False, indent=2))
            for rel in stage_rel:
                z.write(os.path.join(stage_dir, rel), f"stage/{rel}")
            for p in props:
                for rel, b in p["files"].items():
                    z.writestr(f"props/{p['name']}/{rel}", b)
            for rel, b in fx["files"].items():
                z.writestr(f"props/{dlc_particles.EMITTERS}/{rel}", b)
            for src, dst in seq_files:
                z.write(src, dst)
        print(f"  {zpath}: {os.path.getsize(zpath) / 1e6:.1f} MB")
        for p in props:
            print(f"  prop {p['name']}: {len(p['parts'])} parts, {p['vertices']} vertices, {p['materials']} materials, "
                  f"{p['morphs']} morphs, {p['bone_keys']} bone keys, {p['morph_keys']} morph keys, "
                  f"on {p['windows'] if not p['always'] else 'throughout'}")
            for q in p["parts"]:
                print(f"    {q['part']:<12} {q['renderer']:<5} on {q['on']:>4} frames {q['windows']}  rest f{q['rest']} "
                      f"scale {[round(s, 4) for s in q['scale']]}")
            if a.verify:
                err, n = verify_prop(ctx, p, tracks, p["files"][f"{p['name']}.pmx"], p["files"][f"{p['name']}.vmd"])
                print(f"    verify: {n} part-frames, max |error| {err:.2e} game units")
        for c in fx["classes"]:
            print(f"  effect {c['name']!r}: {c['emitters']} emitters ({c['prefix']}NNN), "
                  f"window {c['window'] or 'throughout'}" + (f"; {c['note']}" if c["note"] else ""))
        for path, why in fx["skipped"]:
            print(f"  particles left out: {path} - {why}")
        if a.verify:
            for line in fx["verify"]:
                print(f"    verify: {line}")
        report.append({"seq": seq, "zip": zpath, "props": [p["name"] for p in props],
                       "effects": [c["name"] for c in fx["classes"]]})
    return 0


if __name__ == "__main__":
    sys.exit(main())
